home/urls.py
from django.conf.urls import url
from .views import *
from rss.views import *
from home.views import e_handler404, e_handler500


urlpatterns = [
    url(r'^$', EIndexView.as_view(), name='index'),
    # url(r'^feed/$', ArticlesFeed()),
]



handler404 = e_handler404
handler500 = e_handler500

knowledge/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^$', ENewsIndex.as_view(), name='index'),
    url(r'^(?P<section>[\w]+)/$', ESectionView.as_view(), name='section'),
    url(r'^(?P<section>[\w]+)/(?P<article_id>[0-9]+)/$', EArticleView.as_view(), name='article'),
    # url(r'^comment/(?P<article_id>[0-9]+)/$', EArticleView.post, name='add_comment'),
]

myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import views as sitemap_views      # Представление
from django.contrib.sitemaps import GenericSitemap              # Шаблонный класс для формирования страницы Sitemap
from django.views.decorators.cache import cache_page            # Декоратор кеширования
from knowledge import models as knowledge_models                # Модели статей и разделов, по которым будет формироваться Sitemap
from home.sitemap import HomeSitemap                            # Статический Sitemap для относительно постоянных страниц


# Объект карты разделов. Здесь просто забираются все объекты из базы данных,
# а также по одноимённому полю в модели забирается дата последней модификации
sitemap_sections = {
    'queryset': knowledge_models.Section.objects.all(),
    'date_field': 'section_lastmod',
}

# А вот со статьями уже интереснее. Здесь забираются только те статьи, которые опубликованы
# И для этого нужно будет написать специальный менеджер
sitemap_articles = {
    'queryset': knowledge_models.Article.objects.article_status(),
    'date_field': 'article_date',
}

# Формируем объект со всеми картами и присваиваем им наименования
sitemaps = {
    'sections': GenericSitemap(sitemap_sections, priority=0.5),
    'articles': GenericSitemap(sitemap_articles, priority=0.5),
    'home': HomeSitemap
}


urlpatterns = [
    url(r'^', include('home.urls', namespace='home')),
    url(r'^news/', include('knowledge.urls', namespace='news')),
    url(r'^admin/', admin.site.urls),
]


# Шаблоны URL, заметьте, здесь указано кеширование cache_page(86400)
# Первый шаблон будет формировать основную карту сайта, в которой будут указаны URL дочерних,
# То есть 'sitemap-sections', 'sitemap-articles', 'sitemap-home'
# Заметили, что их названия перекликаются с названиями параметров в объекте sitemaps?
urlpatterns += [
    url(r'^sitemap\.xml$', cache_page(86400)(sitemap_views.index), {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>\w+)\.xml$', cache_page(86400)(sitemap_views.sitemap), {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

knowledge/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from .manager import ArticleManager
from django.contrib.postgres.fields import ArrayField
# Create your models here.


class Section(models.Model):
    class Meta:
        verbose_name = 'Раздел'
        verbose_name_plural = 'Разделы'
        db_table = 'section'

    section_title = models.CharField(verbose_name='Название', max_length=200)
    section_url = models.CharField(max_length=50, verbose_name='ссылка')
    section_description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return self.section_title

    def get_absolute_url(self):
        return reverse('news:section', kwargs={'section': self.section_url})


class Article(models.Model):
    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        db_table = 'article'

    article_name = models.CharField('Название статьи', max_length=200)
    article_section = models.ForeignKey(Section, verbose_name='Раздел')
    article_user = models.ForeignKey(User, verbose_name='пользователь')
    article_date = models.DateField(verbose_name='Дата публикации', auto_now_add=True)
    article_content = models.TextField(verbose_name='Описание')
    article_status = models.IntegerField(verbose_name='Статус')
    objects = ArticleManager()          # объекты queryset подменяются менеджером для расширения функционала

    def __str__(self):
        return self.article_name

    def get_absolute_url(self):
        return reverse('news:article', kwargs={'section': self.article_section.section_url, 'article_id': self.id})


class Comment(models.Model):
    class Meta:
        db_table = 'comments'

    path = ArrayField(models.IntegerField())
    article_id = models.ForeignKey(Article)
    author_id = models.ForeignKey(User)
    content = models.TextField('Комментарий')
    pub_date = models.DateTimeField('Дата комментария')

    def __str__(self):
        return self.content[0:200]

    def get_offset(self):
        level = len(self.path) - 1
        if level > 5:
            level = 5
        return level

    def get_col(self):
        level = len(self.path) - 1
        if level > 5:
            level = 5
        return 12 - level

knowledge/forms.py
from django import forms


class CommentForm(forms.Form):
    parent_comment = forms.IntegerField(
        widget=forms.HiddenInput,
        required=False
    )

    comment_area = forms.CharField(
        label="",
        widget=forms.Textarea
    )

knowledge/views.py
from django.views import View
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator
from django.utils.decorators import method_decorator
from .models import *
from .forms import *
from django.contrib import auth
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.core.exceptions import ObjectDoesNotExist
from django.template.context_processors import csrf
# Create your views here.


class ENewsIndex(View):
    template_name = 'knowledge/index.html'

    def get(self, request, *args, **kwargs):
        context = {}
        context['section_list'] = Section.objects.all().order_by('section_title')
        return render(request, template_name=self.template_name, context=context)


class ESectionView(View):
    template_name = 'knowledge/section.html'

    def get(self, request, *args, **kwargs):
        context = {}
        section = get_object_or_404(Section, section_url=self.kwargs['section'])
        context['section'] = section
        return render(request, template_name=self.template_name, context=context)


class EArticleView(View):
    template_name = 'knowledge/article.html'
    comment_form = CommentForm

    def get(self, request,  *args, **kwargs):
        article = get_object_or_404(Article, id=self.kwargs['article_id'])
        context = {}
        context.update(csrf(request))
        user = auth.get_user(request)
        context['article'] = article
        # Помещаем в контекст все комментарии, которые относятся к статье
        # попутно сортируя их по пути, ID автоинкрементируемые, поэтому
        # проблем с иерархией комментариев не должно возникать
        context['comments'] = article.comment_set.all().order_by('path')
        context['next'] = article.get_absolute_url()
        # Будем добавлять форму только в том случае, если пользователь авторизован
        if user.is_authenticated:
            context['form'] = self.comment_form

        return render(request, template_name=self.template_name, context=context)

    # Декораторы по которым, только авторизованный пользователь
    # может отправить комментарий и только с помощью POST запроса
    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        a = request.POST
        print(a)
        print(self.kwargs)
        form = CommentForm(self, request.POST)
        article = get_object_or_404(Article, id=self.kwargs['article_id'])

        if form.is_valid():
            comment = Comment()
            comment.path = []
            comment.article_id = article
            comment.author_id = auth.get_user(request)
            comment.content = form.cleaned_data['comment_area']
            print(comment)
            comment.save()

            # Django не позволяет увидеть ID комментария по мы не сохраним его,
            # хотя PostgreSQL имеет такие средства в своём арсенале, но пока не будем
            # работать с сырыми SQL запросами, поэтому сформируем path после первого сохранения
            # и пересохраним комментарий
            try:
                comment.path.extend(Comment.objects.get(id=form.cleaned_data['parent_comment']).path)
                comment.path.append(comment.id)
                print('получилось')
            except ObjectDoesNotExist:
                comment.path.append(comment.id)
                print('не получилось')
            comment.save()
        return redirect('/')

knowledge/templates/knowledge/article.html
{% extends 'home/base.html' %}
{% load bootstrap3 %}
{% block page %}
    <article>
        <h1>{{ article.article_title }}</h1>
        {{ article.article_content|safe }}
    </article>
    <h2>Комментарии</h2>
    {% for comment in comments %}
        <a name="comment-{{ comment.id }}"></a>
        <div class="row" id="{{ comment.id }}">
            <div class="col-md-{{ comment.get_col }} col-md-offset-{{ comment.get_offset }}">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <strong>{{ comment.author_id.get_full_name|default:comment.author_id.username }}</strong>&nbsp;&nbsp;
                        {{ comment.pub_date }}
                        <a href="#comment-{{ comment.id }}">#</a>
                    </div>
                    <div class="panel-body">
                        <div>{{ comment.content|safe }}</div>
                        {% if form %}<a class="btn btn-default btn-xs pull-right"
                                        onclick="return show_comments_form({{ comment.id }})">
                            {% bootstrap_icon "share-alt" %}&nbsp;&nbsp;Ответить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    {% if form %}
        <h3 id="write_comment"><a onclick="return show_comments_form('write_comment')">Написать комментарий</a></h3>
        <form id="comment_form" action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">{% bootstrap_icon "comment" %}&nbsp;&nbsp;Комментировать</button>
        {% endbuttons %}
        </form>
    {% else %}
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title">Комментарии</h3>
            </div>
            <div class="panel-body">
                Только авторизованные пользователи могут оставлять комментарии.<br/>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block script %}
    <script>
        function show_comments_form(parent_comment_id) {
            if (parent_comment_id == 'write_comment')
            {
                $("#id_parent_comment").val('')
            }
            else
            {
                $("#id_parent_comment").val(parent_comment_id);
            }
            $("#comment_form").insertAfter("#" + parent_comment_id);
        }
    </script>
{% endblock %}

knowledge/templates/knowledge/index.html
{% extends 'home/base.html' %}
{% block page %}
    <article>
    <h1>Разделы</h1>
    {% if section_list %}
        <ul>
        {% for section in section_list %}
            <li>
            <a href="{% url 'news:section' section.section_url %}">{{ section.section_title }}</a>
            </li>
        {% endfor %}
        </ul>
    {% endif %}
    </article>
{% endblock %}

knowledge/templates/knowledge/section.html
{% extends 'home/base.html' %}
{% block page %}
    <article>
    <h1>{{ section.section_title }}</h1>
        <p>{{ section.section_description|safe }}</p>
        <h2>Статьи</h2>
        <ul>
        {% for article in section.article_set.all|dictsort:'article_title' %}
            {% if article.article_status %}
            <li>
            <a href="{% url 'news:article' section.section_url article.id %}">
                {{ article.article_title }}
            </a>
            </li>
            {% endif %}
        {% endfor %}
        </ul>
    </article>
{% endblock %} 